<?php

return array(
    'faq' => 'Frequently Asked Questions',
    'note' => 'If you have any questions that is not stated above, Please email @ ',
    'call' => 'or Call us at',
    'section' => 'Section',
    'broker' => 'Broker’s Honesty',
    'fund_deposit' => 'Fund Deposit',
    'withdraw_fund' => 'Withdrawing funds',
    'trader' => 'Trader Selection',
    'register' => 'Registration',
    'trading' => 'Trading',
    'become_trader' => 'Becoming a Trader',
    'broker_quetion' => '<p><strong>1. What is the difference between STP (multi lateral) and SPA (dealing desk / dealer) type brokers?</strong></p>The STP broker immediately forwards all orders to the liquidity provider</p><p>Dealing desk / SPA brokers are allowed to act as a market. The customer will always trade with a fixed opponent, that is, the broker itself.</p><p>Because SPA brokers / dealing desks act as a market, often this responsibility is misused for personal gain.</p><p><strong>2. Is our broker OTM or ICDX?</strong></p><p>OTM. STP broker function purely as a liaison between customers to the exchange, namely ICDX. It is in the market where the sellers and buyers meet.</p><p><strong>3. Is this broker honest, how do I know?</strong></p><p>As a broker with an official STP (multilateral) license registered at BAPPEBTI, the server used is the direct exchange server, ICDX. So OTM does not have the power to manipulate transactions that occur.</p><p><strong>4. What is the difference between the ICDX exchange and the SPA broker?</strong></p><p>ICDX as an exchange brings together many parties at once. There are several liquidity providers and interbank markets that are connected to the ICDX exchange as liquidity providers. All transactions from STP (multilateral) brokers will meet on the ICDX exchange.</p><p>While a SPA broker (dealing desk) is a broker which does not forward customer transactions to the exchange. So the customer always deals only with the broker itself (the customer is against the broker).</p><p><strong>5. Will every profit be paid?</strong><p>ICDX in collaboration with ICH (Indonesian Clearing House). ICH functions as GUARANTEE of all customer transactions.</p><p>ICH also accommodates all funds from customers and liquidity providers. This is useful to ensure that every customer’s profit must be paid.</p><p><strong>6. Has this ICDX concept ever been used in the world?</strong></p><p>This concept is the first in Southeast Asia and the second in the world after Tokyo.</p><p><strong>7. Is OTM an official broker?</strong></p><p>Yes, OTM is an official broker in Indonesia registered with BAPPEBTI with STP (multilateral) permission, not Dealing desk (SPA)</p><p><strong>8. Other brokers are also registered with BAPPEBTI, but not necessarily honest</strong></p><p>As of this writing (April 15, 2020), OTM is the only broker with a STP (multilateral) permit from BAPPEBTI in Indonesia. It is the nature of this STP that guarantees every transaction actually take place on the exchange. All transactions are transparent, safe, honest and straightforward.</p><p><strong>9. Can I visit OTM or the ICDX Exchange?</strong></p><p>You can visit OTM or ICDX. ICDX Exchange is also open for people who want to learn about products & transactions on the exchange. Please make an appointment to visit.</p><p>',
    "fund_deposit_que"=>"<p><strong>1. Why use Rupiah, not Dollar?</strong></p><p>a. There are restrictions from the government, that the maximum foreign exchange transactions are $ 25,000 per month. If it’s more than that, there must be an underlying.</p><p>b. By using Rupiah, customers are free to deposit any amount and at any time.</p><p>c. There is no exchange rate difference which will be a cost to the customer</p><p><strong>2. How much is the cost for copy trade?</strong></p><p>2-5% depending on the amount of funds deposited. The greater the funds, the smaller the cost of copy trade. Funds are only paid once at the time of deposit</p><p><strong>3. Why should there be a copy trade fee?</strong></p><p>Because we have to pay fees for employees, servers, technology, etc.</p><p><strong>4. Is there any costs to buy a trading robot?</strong></p><p>No</p><p><strong>5. Where can I transfer the fund?</strong></p><p>a. Funds for the trade can be transferred to OTM Kapital Berjangka - BCA Rupiah Account 035 3250 881</p><p>b. Copy trade fees can be transferred to PT Avanya Xcellence Indonesia - BCA 372 184 0075</p><p><strong>6. Can I transfer from any account?</strong></p><p>a. You cannot, funds must be transferred from an account that has been registered.</p><p>b. The account must be from the same name as the one registered</p><p><strong>7. Can I get the transfer proof of my funds from OTM to the ICH clearing agency?</strong></p><p>You can. Kindly inform us before making a transfer to OTM.</p>",
    "withdrawing_que"=>"<p><strong>1. When can I stop trading?</strong></p><p>The trade will close all positions every month. You can stop at any time, but positions that are currently floating will be automatically closed, whether they are in a profit or loss position.</p><p><strong>2. Are there fees for capital & profits withdrawals?</strong></p><p>There aren’t.</p><p><strong>3. Are there any fees for withdrawing referral bonuses?</strong></p><p>There aren’t.</p><p><strong>4. When can I withdraw capital and profits?</strong></p><p>Anytime. But the trade will close a position every month. Positions that are currently floating will be automatically closed, whether they are in a profit or loss position.</p><p><strong>5. How long will the capital withdrawal take?</strong></p><p>a. Capital withdrawals before 11:00 WIB will proceed on the same day. After that, will proceed on the next working day.</p><p>b. Withdrawals will be processed on weekdays and working days.</p><p><strong>6. How long does the withdrawal of referral bonuses take?</strong></p><p>Profit withdrawals will be processed every weekend, and will proceed on the next week.</p><p><strong>7. Can funds go into any account?</strong></p><p>a. Cannot, funds must be transferred from an account that has been registered.</p><p>b. The account must come from the same name as the one registered<p><strong>8. Does my profit include tax?</strong></p><p>Yes, transaction tax is included. But not income tax.</p>",
    "trader_que"=>"<p><strong>1. Can I choose a trader?</strong></p><p>You can.</p><p><strong>2. Can I choose several traders at once?</strong></p><p>You can. Please determine how much funds are allocated for each trader.</p><p><strong>3. How much funds should I put into each of the selected traders?</strong></p><p>a. It depends on your age and courage to take isks</p><p>b. As a person ages, it is advisable to put more funds into a safer trader</p><p><strong>4. Are the traders whose results are bigger translates into greater risk?</strong></p><p>It’s usually that way.</p><p><strong>5. Which trader should I choose?</strong></p><p>a. Traders who match the results you want</p>b. Traders whose risks you can accept<p><strong>6. Why are there traders who are labeled as high risk?</strong></p><p>a. These traders usually use techniques that can get very arge results in a short time.</p><p>b. This technique also allows one to lose large amounts of money in a short amount of time</p><p><strong>7. If my chosen trader experiences a loss, will my money be returned?</strong></p><p>No</p><p><strong>8. Is there a guarantee that the trade must be profitable?</strong></p><p>No</p><p><strong>9. What is a drawdown?</strong></p><p>The amount of floating loss that ever happened. Floating loss does not necessarily mean loss, it could be in the floating process.</p>",
    "register_que"=>"<p><strong>1. I registered on the Avanya website. Does that mean I'm already registered with an OTM broker?</strong></p><p>
Because Avanya has signed an official cooperation agreement with OTM, all registration data in Avanya will be directly entered and officially processed by OTM.</p><p><strong>2. Why does the data that must be filled is so long?</strong></p><p>OTM is a broker registered officially at BAPPEBTI. Then the data needed is in accordance with government regulations</p><p><strong>3. How long does it take to process registration?</strong></p><p>Around 2 working days.</p><p><strong>4. Why do I have to be phoned by an OTM broker representative?</strong></p><p>OTM is a broker registered officially at BAPPEBTI. So according to government regulations, the OTM broker must ensure that you really have registered and opened a trading account. You also understand the risks that will be taken.</p><p><strong>5. I have registered with another broker, can OTM automatically retrieve my registration data?</strong></p><p>It can not.</p>",
	"trading_que"=>"<p><strong>1. What currencies will the trader trade?</strong></p><p>a. This depends on the preferences of each trader.</p><p>b. ICDX Exchange provides major pairs, gold and crossrate products. All of these products can be transacted by OTM customers.</p><p><strong>2. Why can’t I see which pair is being used upon the live trade?</strong></p><p>To protect the revenue share with Avanya, the pair currently being used is not indicated</p><p><strong>3. Is live transactions delayed? If it is, how many seconds delay?</strong></p><p>All transactions are completely live, there is no delay</p><p><strong>4. Who can be a trader?</strong></p><p>Anyone who has experience in trading, please register. Avanya will conduct a selection process.</p><p><strong>5. Can I meet the traders that I copy from?</strong></p><p>We will respect the wishes of traders. If the trader permits this, we will arrange an official meeting.</p><p><strong>6. Do all trades have to be done at an OTM broker?</strong></p><p>Yes</p><p><strong>7. How does the auto stop feature work?</strong></p><p>a. The auto stop amount is set based on the character of each trader. A more conservative trader will have a smaller auto stop.</p><p>b. Maximum auto stop value is 30%. When floating loss reaches 30%, all positions will be closed automatically.</p><p><strong>8. Is there a possibility that the auto stop will be missed?</strong></p><p>a. Although the probability is very small, but this possibility could happen.</p><p>b. This could happen when the market is moving very fast and is not liquid enough.</p><p><strong>9. Where does my profit go to?</strong></p><p>Profit will unite with your capital. It will remain there until you decide the withdraw it. Only you can withdraw your profit.</p><p><strong>10. How much is the profit sharing?</strong></p><p>Customer: Avanya = 60:40 and 70:30, depending on the amount of funds deposited</p><p><strong>11. Can I trade alone?</strong></p><p>You can not, because of the profit sharing system. However you can apply to become a trader on Avanya.</p>",
	"become_trader_que"=>"<p><strong>1.Can I register as a trader?</strong></p><p>You can. Trader registration is open to anyone.</p><p><strong>2. What is the selection process like?</strong></p><p>a. Fill in the registration form</p><p>b. Open an account at OTM and trade with your own funds</p><p>c. After there is good result for at least 3 months, then investors may choose you.</p><p>d. During these 3 months, there should not be a loss month</p><p><strong>3. How big is the profit sharing for the trader?</strong></p><p>5% of profit.</p><p><p><strong>4. Why isn't the profit sharing for traders as big as I imagined?</strong></p><p>Most of the profit sharing is given to referral bonuses for those who look for investors. With many investors, the profit sharing will surely increase by itself.</p><p><strong>5. Can I use a bot?</strong></p><p>You can</p><p><strong>6. Do I have to trade on OTM?</strong></p><p>Yes</p><p><strong>7. Can I become a trader elsewhere?</strong></p><p>a. You can, but for trade results that are copied by Avanya customers, it cannot be used elsewhere.</p><p>b. You must create another portfolio to be used elsewhere.</p><p><strong>8. Why are there trading techniques that are categorized as high risk?</strong></p><p>Because this technique has the potential to produce big loss when the market reverses direction.</p><p><strong>9. How long does the portfolio must be before it can be copied?</strong></p><p>3 months</p><p><strong>10. Why can't I hedge?</strong></p><p>In accordance with exchange and BAPPEBTI rules, hedging is not permitted. This no hedging rule also applies in exchanges throughout the world.</p>",

);
